### ISSUE TITLE
Clarity on folder structure

### ISSUE THREAD

**Issue by AlexKalopsia** [grimsi/gameyfin#134]
I am struggling to understand what is the recommended mode of use and folder structure, feels like README could bring some more clarity.

Say I have a bunch of pc games, ps2 games, and xbox games. Is it recommended to mount 3 volumes for 3 different libraries? Or should all of the titles be under one library? Can these still be separated in subfolders?

Thanks

**Comment by grimsi** [comment]
Both is possible. IMO the cleaner way would be to have different mounts (the mounts can still be in the same parent folder on your host), but Gameyfin doesn't know or care how you mount the library into the container
