### ISSUE TITLE
Allow for a different database storage backend

### ISSUE THREAD

**Issue by colonelpopcorn** [grimsi/gameyfin#150]
**Is your feature request related to a problem? Please describe.**
I want to be able to query data separately from gameyfin, and use other tools to analyze the database generated by gameyfin's repositories.

**Describe the solution you'd like**
Add a configurable way to use a different storage backend. e.g. SQLite, MySQL, MSSQL, PostgreSQL, etc.

**Describe alternatives you've considered**
I could see if there's an easy way to query an h2 database, but when I'm looking at services like this I like to have my pick of DB tech.

**Additional context**
Spring should have an easy way to do this already, maybe there could just be a wiki article added to show how to configure Spring for various DB stacks.

**Comment by grimsi** [comment]
This should already be possible, as you said Spring Data should support it out-of-the-box.
Did you have any problems following official Spring documentation?

**Comment by colonelpopcorn** [comment]
I haven't tried it yet, but you are correct there are ways to override the datasource properties file. However, I'm not sure that the migrations generated by JPA will work across all providers. I know SQLite uses `TEXT` instead of `VARCHAR`, but it will accept VARCHAR as an argument to create a text field. Is there a way we could do this without requiring the user to recompile/redeploy a docker container? If not, would it be possible to have docker containers tagged with a specific DB provider?

**Comment by grimsi** [comment]
Custom DB providers outside of what Spring Data offers wont be a thing. The use case for this is just too niche while the maintainance would be a fair amount of work.
