### ISSUE TITLE
Does this work on linux?

### ISSUE THREAD

**Issue by DOOMMARINE117** [grimsi/gameyfin#152]
what is this basically? a manager or can you use it to install games with like lutris?

**Comment by m3shat** [comment]
Desregarding that it kinda looks dead to me; it's a Webui to organize and download game (installer) files from a server. 
Very niche IMHO, kinda only useful for datahoarding (like me hehe).
You can install it on a linux machine of course but I don't think it'll bring that much to the table if you don't plan on sharing the game (installer) files over the network.

Lutris is not a good comparison. Think more like file archive.

**Comment by grimsi** [comment]
Yes sorry, I currently have very little time available.
The project is not dead, but it is on a hiatus.

To answer your question: It should work on Linux since it's a Java application.
Think of it as a library for your games
