### ISSUE TITLE
diferent volume location for DB

### ISSUE THREAD

**Issue by pmmota** [grimsi/gameyfin#153]
**Is your feature request related to a problem? Please describe.**
not exactly a problem but a method to have the container deploy the db on a different volume than the volume where the games exist

**Describe the solution you'd like**
possible to have an evironment variable for the DB

**Comment by pmmota** [comment]
btw I am reffering to the .gameyfin folder that gets created when the container starts.

**Comment by grimsi** [comment]
Maybe not a real fix, but you could try this as a workaround:
Set multiple source folders, Gameyfin will create the .gameyfin folder in the first source folder.

**Comment by grimsi** [comment]
Setting `gameyfin.folders.data` will achieve what you want. Sorry, I totally forgot that I already implemented this already.
If the property is not set, it will use the first library folder to create the .gameyfin folder
