### ISSUE TITLE
Implement in-browser game players

### ISSUE THREAD

**Issue by colonelpopcorn** [grimsi/gameyfin#176]
**Is your feature request related to a problem? Please describe.**
As a user of gameyfin, I would like to be able to play games directly in my browser so I can browse and start up a game directly without having to context switch to a different application after download.

**Describe the solution you'd like**
Embedding an emulator like [RetroArch web player](https://docs.libretro.com/guides/web-player/), [EmulatorJS](https://emulatorjs.org/), or [Nostalgist](https://github.com/arianrhodsandlot/nostalgist).

**Describe alternatives you've considered**
[Retroarcher](https://retroarcher.github.io/) implements a streaming server similar to moonlight/sunshine/parsec, but I think local resources would be better to run the games.

**Additional context**
N/A

**Comment by grimsi** [comment]
Thanks for your suggestion. However I think that this is out-of-scope for Gameyfin.
I developed Gameyfin mainly as a tool to quickly share games with friends (I use it myself for LAN parties) and I would like to avoid feature creep.
