### ISSUE TITLE
Enhancement Request: put Gameyfin version in footer

### ISSUE THREAD

**Issue by jshackles** [grimsi/gameyfin#22]
It would be nice if the footer at the bottom of the page listed the version of Gameyfin that was currently running (maybe next to the Github link?).  This might also help future troubleshooting issues to give users a way to quickly know if they are running the latest version or not.

Thanks.  Keep up the good work!

**Comment by grimsi** [comment]
Nice idea, will be part of the next release. But I can't promise when that will be.
