### ISSUE TITLE
Unsupported database file version or invalid file header

### ISSUE THREAD

**Issue by TimmyYung** [grimsi/gameyfin#237]
**Describe the bug**
When starting up the container for Gameyfin, it automatically turns off due to an "Unsupported database file version...". The main lines from the log that I think is the error are these two lines

- Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Unsupported database file version or invalid file header in file "/opt/gameyfin-library/.gameyfin/db/gameyfin_db.mv.db" 
- Caused by: org.h2.mvstore.MVStoreException: The write format 2 is smaller than the supported format 3

**To Reproduce**
1. Run the container using "docker start"
2. See error in logs

**Expected behavior**
The container should start up and be viewable through a browser. 

**General info (please complete the following information):**
 - Installation method: docker version 25.0.2
 - Gameyfin version: Using :latest. Currently that is v.1.4.5

**Additional context**
Attached are the logs
[_gameyfin_logs.txt](https://github.com/grimsi/gameyfin/files/14154248/_gameyfin_logs.txt)

**Comment by grimsi** [comment]
Looks like your database got corrupted during an update. Can you try deleting the database file (in "/opt/gameyfin-library/.gameyfin/db/gameyfin_db.mv.db" or the corresponding mount point on your host).
Note: This means that you will have to re-index your libraries.

**Comment by TimmyYung** [comment]
> Looks like your database got corrupted during an update. Can you try deleting the database file (in "/opt/gameyfin-library/.gameyfin/db/gameyfin_db.mv.db" or the corresponding mount point on your host). Note: This means that you will have to re-index your libraries.

Thank you! This solution works by deleting the "/opt/gameyfin-library/.gameyfin/db/gameyfin_db.mv.db".
