### ISSUE TITLE
Support for games from other platforms

### ISSUE THREAD

**Issue by Pfuenzle** [grimsi/gameyfin#31]
I have been using your program for a few days now and am really happy with it, for Windows games this is everything one could ask for.

One thing that could be an improvement to the program itself is support for other platforms.
Since the program is already fully functional and IGDB has games from most other platforms (at least consoles) and from my experience looking into the code, adding support for other platforms should not require that much of a change.

Have you already thought about something like this?
If not, what do you think about this?

### Possible Implementation
One possible implementation and the one I think of as the best one would be the usage of the library system.
Currently, you can add multiple libraries with windows games. To support multiple platforms, there would just need to be a mapping, which library contains games from which platform.
```
/opt/gameyfin-library/Windows -> Windows
/opt/gameyfin-library/Gameboy -> Gameboy
```
This would require a list of possible platforms supported by IGDB, Then, when parsing a library, `preferredPlatforms` would just not need to be read from the Gameyfin config, but from the library config and it should work.
As Gameyfin lets the user download the whole folder, at this part only the extra extensions like `.gb, .gba etc..` should have to be added.
As for the main page, I think only another filter for platform would have to be added so users could filter out linux games e.g.

#### Library setup
As for how the user sets up his libraries, there are two possibilities:

1. Create a new settings page, where the user could add a new library with a textfield for the path and a dropdown field for the game platform. Then the library config gets saved to a config file somewhere. This would require more initial work, but would be more intuitive and a cleaner approach.

Another bonus this kind of implementation would enable is the support of emulators for platforms, that when adding a new library, a third field could be added to select, which emulator can be used with the chosen platform. With this, an end user could download the Gameboy Game XYZ and next to it directly the matching emulator

2. Just let the user input his library choice in the config/docker-compose.yml, but also let him map a platform to the library
(This is just some example, I'm sure there are better ways to do this)
`- GAMEYFIN_SOURCES=/opt/gameyfin-library/mywindowsgames|WINDOWS, /opt/gameyfin-library/gameboy|GAMEBOY`
This would require less coding work, but would be not as clean and more unintuitive

Those are just my two cents on this topic, but in my opinion support for more platforms would be really great addition for this program with comparatively little additional work due to the great base. Also, if not for console games, I think this would be great to differentiate Windows, Linux and MacOS games, as I currently have to decide between one of them.

Thanks for reading :)

**Comment by grimsi** [comment]
Oh wow this would be indeed an awesome feature. I think this fits well with the also requested account system.
However I really have to think about priorities now since I got a lot of new feature requests in the last days and some features (like this) may seem easy on the surface but are most likely more complex once I start the implementation.

**Comment by Pfuenzle** [comment]
I could definitely try to implement this so you can focus on the other features.
I also thought about working on the torrent support so I'm not sure whats better to work on/if you want to do the torrent implementation yourself

**Comment by jshackles** [comment]
+1 for this, I think this sounds amazing.

**Comment by shawly** [comment]
I'm currently adding platforms support, but I'm not fully finished yet so you'll have to wait a little longer.

You can track my changes here: https://github.com/shawly/gameyfin/tree/feature/add-platforms
