### ISSUE TITLE
Installing on Synology Docker

### ISSUE THREAD

**Issue by foerl** [grimsi/gameyfin#36]
i've mapped my gamelibrary during the synology docker installation as Environment Variable: 

VOLUMES          /volume1/Downloads/Games:/opt/gameyfin-library/library-1

and put some GOG games in there but nothing is showing. i had them in folders e.g. /volume1/Downloads/Games/GOG/game.exe and just as .exe /volume1/Downloads/Games/game.exe. 

i can only see: /opt/gameyfin-library/.gameyfin as unmapped file. 

what format do the games need to be? 

i didn't have any luck using portainer with gameyfin added as custom template: 
version: "3"
services:
  gameyfin:
    image: grimsi/gameyfin:latest
    container_name: gameyfin
    environment:
      - GAMEYFIN_USER=xxx
      - GAMEYFIN_PASSWORD=xxx
      - GAMEYFIN_IGDB_API_CLIENT_ID=xxx
      - GAMEYFIN_IGDB_API_CLIENT_SECRET=xxx
      - GAMEYFIN_SOURCES=/opt/gameyfin-library/library-1
    volumes:
      - /volume1/Downloads/Games:/opt/gameyfin-library/library-1
    ports:
      - "49195:8080"

**Comment by Pfuenzle** [comment]
As the unmapped file is under /opt/gameyfin-library/ instead of :/opt/gameyfin-library/library-1, it looks like GAMEYFIN_SOURCES does not get honored. Maybe it does not work when only using 1 library? Would be weird, but maybe...

As you only have one library, you could try to use https://github.com/grimsi/gameyfin/blob/main/docker/docker-compose.example.yml this docker-compose, maybe this works better.

**Comment by grimsi** [comment]
Is this bug still occuring in the newest version?

**Comment by Ithiloneth** [comment]
I think I'm having a related (if not the same) issue on v1.3.2

The Container starts, and I can use the web client but the libraries aren't there as one would expect.

```version: "3"
services:
  gameyfin:
    image: grimsi/gameyfin:latest
    container_name: gameyfinserver
    environment:
      - PUID=XXX
      - PGID=XXX
      - GAMEYFIN_USER=XXX
      - GAMEYFIN_PASSWORD=XXX
      - GAMEYFIN_IGDB_API_CLIENT_ID=XXX
      - GAMEYFIN_IGDB_API_CLIENT_SECRET=XXX
      - GAMEYFIN_SOURCES=/opt/gameyfin-library/library-1,/opt/gameyfin-library/library-2
    volumes:
      - /volume1/Archive/HL_Drop/Public/Game:/opt/gameyfinserver/gameyfin-library/library-1
      - /volume1/Archive/Organized/Public/Game:/opt/gameyfinserver/gameyfin-library/library-2
    ports:
      - "8097:8080"```

![image](https://github.com/grimsi/gameyfin/assets/20944949/69d32e10-4dc9-41b7-816c-908c324f2976)
![image](https://github.com/grimsi/gameyfin/assets/20944949/1b9084d7-61d8-4012-ab84-ccdc55889289)
![image](https://github.com/grimsi/gameyfin/assets/20944949/8543be6f-3a46-4bf4-919a-a8ec13905e41)

**Comment by grimsi** [comment]
You have mismatched paths:
`/opt/gameyfin-library/library-1,/opt/gameyfin-library/library-2` in your GAMEYFIN_SOURCES
`/opt/gameyfinserver/gameyfin-library/library-1` in your Docker volume mounts

**Comment by Ithiloneth** [comment]
I think that might have solved my problem; it causes me to run into another one however:
```
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: IO Exception: "java.nio.file.AccessDeniedException: /opt/gameyfinserver/gameyfin-library/library-1/.gameyfin/db"; "/opt/gameyfinserver/gameyfin-library/library-1/.gameyfin/db" [90031-214]
```

I'd be grateful for help, though I understand if this is not the place for it or if you don't have time. Other containers work fine and I use much the same setup (I.E the same Docker root folder for the containers and same root folder for media) without any permission failures.
Those containers were set up using the GUI, so I tried doing that for Gameyfin as well, thinking the GUI might be enabling the permissions - didn't help.

**Comment by grimsi** [comment]
Tracked in #119
