### ISSUE TITLE
[Feature Request] Upload Custom Cover Arts

### ISSUE THREAD

**Issue by DebugDax** [grimsi/gameyfin#39]
Hello,

Could you please implement a way to override a games Cover art? Currently IDGB pulls cover arts with various resolutions and it makes the library lose its uniformity.

I imagine this could be implemented by just having it prioritize if there's a "cover.jpg/png" in the games sub folder or named after the same game ZIP then it will use that over the IDGB cover.

example:

game-library/Toy Story/Toy Story.zip
game-library/Toy Story/Toy Story.png

or

game-library/Toy Story.zip
game-library/Toy Story.png

![image](https://user-images.githubusercontent.com/6743505/194889700-a798d0fd-23ab-4d46-a235-20e1f5012e27.png)

**Comment by grimsi** [comment]
Possible duplicate of #38

**Comment by DebugDax** [comment]
Yeah I saw that one but figured it was more broad than this so they would be considered separate features. Editing an entries information vs support for loading images from folder as covers. 

Feel free to close if too similar!
