### ISSUE TITLE
[Feature Request] Manually Refresh Individual Games

### ISSUE THREAD

**Issue by DebugDax** [grimsi/gameyfin#45]
It would be nice to have a way to manually refresh individual games if the files change for that game.
This could update the filesize of the download, and pull new metadata from IGDB.

![image](https://user-images.githubusercontent.com/6743505/195337329-0b551b06-36d9-4afc-81d6-ff097fba42e7.png)

Opened as requested in #37

**Comment by shawly** [comment]
https://github.com/grimsi/gameyfin/pull/57 will add this :)

**Comment by grimsi** [comment]
Thanks again for your contribution @shawly !
The feature has been merged and will be part of the next release (1.2.4)
