### ISSUE TITLE
Investigate problems with maven build

### ISSUE THREAD

**Issue by grimsi** [grimsi/gameyfin#46]
@tr7zw and @Pfuenzle both had problems while setting up their development environment.

This issue should serve as a space for discussion and investigation.

**Comment by grimsi** [comment]
I set up the repository on a new computer today (one which I hadn't used before to develop Gameyfin) and did not run into any of the problems you mentioned.
I also set up a simple CI pipeline today which also worked without problems: https://github.com/grimsi/gameyfin/actions/runs/3235721407

Since Java should be cross-platform and I personally use both Windows and Linux I think we can rule that out.
My current guess is that it has something to do with the JDK. I personally use Termurin 18 (https://adoptium.net/) and that's what I also configured in the CI pipeline to be used.
Which JDK vendor and version are you using?

**Comment by Pfuenzle** [comment]
Oh right, forgot about that but yes, I'm using the Oracle one

**Comment by tr7zw** [comment]
I had the issue using Termurin 18.
```
java --version
openjdk 18.0.2.1 2022-08-18
OpenJDK Runtime Environment Temurin-18.0.2.1+1 (build 18.0.2.1+1)
OpenJDK 64-Bit Server VM Temurin-18.0.2.1+1 (build 18.0.2.1+1, mixed mode, sharing)
```

**Comment by grimsi** [comment]
Well that debunks my theory then.
I'm honestly at a loss because for me it just doesn't make sense, but since both of you had the same problem something must be wrong.

**Comment by tr7zw** [comment]
Since the ``<optimizeCodegen>false</optimizeCodegen>`` solution came up a few times, guess that "optimized Codegen" is just a bit janky in general.

**Comment by grimsi** [comment]
Alright, I added this configuration and it's part of release 1.2.3 (https://github.com/grimsi/gameyfin/releases/tag/v1.2.3).

However I will leave this issue open in case this does not solve the problem.

BTW, the docs have the following info on the `optimizeCodegen` parameter: `If "true", skip code generation when .proto input files appear unchanged since last compilation.`

**Comment by grimsi** [comment]
Since I heard nothing contrary from you I'm going to assume that this issue can be closed 🙂
