### ISSUE TITLE
[1.3.0] Can't link a platform to a library

### ISSUE THREAD

**Issue by totof-l** [grimsi/gameyfin#71]
### **What happens ?**

Can't select a platform, happen on any library, to any platform.

### **What are the steps to reproduce this issue ?**

Gameyfin > Library management > Library mappings > "Edit" icon (pencil)
On the "IGDB Platform Slugs", type a platform (e.g. : "Windows") > Select a platform
"PC (Microsoft Windows)" > Select the "OK" button > Error > Error > Error

![image](https://user-images.githubusercontent.com/66698742/198246519-1395563c-ec23-4517-bea7-6719a0b079b4.png)

![image](https://user-images.githubusercontent.com/66698742/198243262-0facee0d-3104-4784-833f-852ee4b12241.png)

### **What were you expecting to happen ?**

To link a platform to a library
It's a new feature (see #31 and https://github.com/grimsi/gameyfin/releases/tag/v1.3.0)

### **Any other comments ?**

Thanks for this program, it's really great, easy and clean ! 👍 

I've tried to set a new instance of gameyfin, same issue.
Also the same error occur if I try other platforms (Switch, Dreamcast, GameBoy...)

_**Does this new feature requires some changes in the docker-compose file ?**_

With the UnRaid version, there is no log files generated (or I don't know how to add it)

### **What versions of software are you using ?**

v1.3.0

### **Operating System ?**

UnRAID (with Docker)

**Comment by grimsi** [comment]
Yes, can confirm the bug and already fixed it :)
I released 1.3.1 with the fix, can you please confirm that it works now?

Thanks for reporting!

**Comment by totof-l** [comment]
It is working on v1.3.1 :)
Thanks for the quick fix !
