### ISSUE TITLE
Support multiple game library folders

### ISSUE THREAD

**Issue by grimsi** [grimsi/gameyfin#8]
Currently only one folder as game library is supported, however a user on reddit suggested supporting multiple folders: https://www.reddit.com/r/selfhosted/comments/wl93p9/comment/ijsng3a/?utm_source=share&utm_medium=web2x&context=3

**Comment by grimsi** [comment]
This feature is now implemented and will be part of release 1.1.0

**Comment by Code-Slave** [comment]
Thanks for this

**Comment by Shadowfita** [comment]
Hi @grimsi , I'm loving this so far. Just wondering if it's possible to utilise multiple folders with docker? Can't find a way. Thanks.

**Comment by grimsi** [comment]
Yes it is supported. In the docker folder there are two different docker compose example files, one of them is for multiple folders.
