### ISSUE TITLE
Toggle autohide filterdropdown menus

### ISSUE THREAD

**Issue by SpoonLoeffel** [grimsi/gameyfin#86]
**Is your feature request related to a problem? Please describe.**
I find it really annoying that the dropdown menus for the filter options automatically close after deselecting the last ticked option. My expected behaviour is that they should stay opened until i leave the page or close them manually.

**Describe the solution you'd like**
I would like if there was an option for if they should automatically close or not after deselecting everything.

**Describe alternatives you've considered**
Alternatively an Option for their default state opened or closed, would be nice. Or maybe even both.

**Comment by grimsi** [comment]
Thanks for the bug report!
I am already aware of this and it will be part of the next release.
However I do not have a lot of time I can spend on Gameyfin so expect it to take a few more weeks.
