### ISSUE TITLE
Feature Request: Sorting

### ISSUE THREAD

**Issue by jshackles** [grimsi/gameyfin#9]
Excellent application, I'm impressed!

It would be cool to be able to sort by:

- Alphabetical (A-Z is already default / Z-A)
- Game release date (newest / oldest)
- Date game was added to Gameyfin (newest / oldest)
- Game rating (best / worst) I believe IGDB has this data if you're not already capturing it

Thanks for your consideration!

**Comment by grimsi** [comment]
Thanks for your feedback! I do indeed already save the ratings (I even display them in the game detail view, although not as fancy as in the IGDB website).
I will look into your suggestion.

**Comment by grimsi** [comment]
Scope of this feature:

- [ ] Implement "Added to library" property
- [ ] Sort library by Title / Release Date / Added to library / Rating
- [ ] Make sorting options on the sidebar collapsible (collapsed by default)
- [ ] Store sorting preferences in the url as parameters and read them from there (makes it easy to bookmark)
