### ISSUE TITLE
Please provide arm64 image

### ISSUE THREAD

**Issue by XargonWan** [grimsi/gameyfin#93]
**Is your feature request related to a problem? Please describe.**
I cannot deploy it on my raspberry pi.

**Describe the solution you'd like**
An image for arm64

**Describe alternatives you've considered**
I don't have an alternative atm.

**Comment by grimsi** [comment]
Thanks for your input!
I agree, not providing ARM64 images is an oversight from me.
I will take a look at it and will try to publish an ARM64 image with the next Gameyfin release.

**Comment by GAntoine** [comment]
I just saw that someone on Reddit pushed [a build of v1.3.2 for `arm64/v8`](https://hub.docker.com/r/arcaneasada/gameyfin/tags). It should tide you over until [Github supports arm64 runners](https://github.com/actions/runner-images/issues/5631).

**Comment by fede843** [comment]
Nice, an official image for arm would be just great. Thanks!

**Comment by grimsi** [comment]
ARM builds will be part of the 1.4.2 release.
You can already test it with the `1.4.2-DEV` tag: https://hub.docker.com/layers/grimsi/gameyfin/1.4.2-DEV/images/sha256-d57166e89d5889d95c8a13dc92b8b7e08681d2ceee9abc6f4b8352449cef7211

**Comment by grimsi** [comment]
Part of 1.4.2, closing this issue.
