### ISSUE TITLE
Add API endpoint to get game files

### ISSUE THREAD

**Issue by HEPOSHEIKKI** [grimsi/gameyfin#97]
**Is your feature request related to a problem? Please describe.**

I am currently writing a desktop client for gameyfin. Everything works as expected and the launcher/client is completely functional, but I do not consider the code to be clean enough yet. My main problem right now is the way games are downloaded. Currently games get packed into a zip container and then distributed, I'd like an alternative as described below.

**Describe the solution you'd like**

Add an API endpoint that returns a JSON with URLs to all the individual files of a game, as well as optional md5 hashes for the files and the number of files in the game. This would significantly speed up downloads and the setup especially when using a desktop client as we can now perform a hash check and a download at the same time. This will also make it easier to resume downloads if a connection is interrupted.

**Comment by Toylerrr** [comment]
Currently you can veiw the whole library via 127.0.0.1:8080/v1/games/

The basic format of the download url is 127.0.0.1:8080/v1/games/game/"NAME SLUG"/download

```
{"slug":"the-elder-scrolls-iv-oblivion","title":"The Elder Scrolls IV: Oblivion","summary":"The Elder Scrolls IV: Oblivion, the fourth game in the Elder Scrolls story, is set within the province of Cyrodiil, the heartland and Imperial capital of Tamriel. Emperor Uriel Septim VII is assassinated in flight from his own palace, but just before he dies he passes on to you the mystic Amulet of Kings. The adventure proper begins with the quest to find Uriel's lost and illegitimate son who is the only heir to the throne. In a world where the forces of darkness seek their ultimate dominion over the ranks of man and mer alike, you alone stand between the future of Tamriel and the gates of Oblivion.","releaseDate":"2006-03-20T00:00:00Z",
```
So for Oblivion the DL link would look like 127.0.0.1:8080/v1/games/game/the-elder-scrolls-iv-oblivion/download


I know it doesnt 100% solve what you were trying to request from this but there is an endpoint that you can pull information form.

**Comment by HEPOSHEIKKI** [comment]
> Currently you can veiw the whole library via 127.0.0.1:8080/v1/games/
> 
> The basic format of the download url is 127.0.0.1:8080/v1/games/game/"NAME SLUG"/download
> 
> ```
> {"slug":"the-elder-scrolls-iv-oblivion","title":"The Elder Scrolls IV: Oblivion","summary":"The Elder Scrolls IV: Oblivion, the fourth game in the Elder Scrolls story, is set within the province of Cyrodiil, the heartland and Imperial capital of Tamriel. Emperor Uriel Septim VII is assassinated in flight from his own palace, but just before he dies he passes on to you the mystic Amulet of Kings. The adventure proper begins with the quest to find Uriel's lost and illegitimate son who is the only heir to the throne. In a world where the forces of darkness seek their ultimate dominion over the ranks of man and mer alike, you alone stand between the future of Tamriel and the gates of Oblivion.","releaseDate":"2006-03-20T00:00:00Z",
> ```
> 
> So for Oblivion the DL link would look like 127.0.0.1:8080/v1/games/game/the-elder-scrolls-iv-oblivion/download
> 
> I know it doesnt 100% solve what you were trying to request from this but there is an endpoint that you can pull information form.

Yes, I am aware and my client currently uses that api, but it returns zip files which is not optimal.

**Comment by grimsi** [comment]
> Yes, I am aware and my client currently uses that api, but it returns zip files which is not optimal.

This is by design since there is no possibility (that I know of) to download a directory structure in a browser.
Since the web UI is the only official Gameyfin frontend I won't implement client-specific endpoints at the moment (due to limited time), but I may accept pull requests for such a feature.
